### ISSUE TITLE
Crash to Desktop on completing ingame-objective

### ISSUE THREAD

**Issue by ktElwood** [jdmclark/jkgfxmod#61] opened 2020-10-15 14:17 UTC
Hello,

I installed the "JK_Remastered" Mod, and while running around in my old savegame (Fueling Station) Everything works fine. On completion of the objective (go through fuel tank) however the game crashes to desktop (when you jump from the tank to the next elevator)

How can I help to find the issue here ?

**Comment by jdmclark** [comment] 2020-11-09 15:30
Hi @ktElwood 

The JK Remastered mod includes many mods, any of which may be the root cause. I believe this includes an FOV patch, which is known to cause crashes by itself in JK and MotS.

Please let me know if you can reproduce this crash with only JkGfxMod installed (and all other mods uninstalled).

Otherwise, I recommend contacting the maintainer of the JK Remastered Mod.

Thanks

**Comment by tgies** [comment] 2020-11-10 04:55
> while running around in my old savegame

Can attest that reusing old savegames with different mods installed will crash JK randomly, JkGfxMod or no.

**Comment by jdmclark** [comment] 2020-11-10 14:50
It sounds like the root cause was reusing a previous save (i.e. a JK problem, not a JkGfxMod problem). Our doc already recommends starting a new game, so what we can do is already done. Closing as invalid.

**Closed as completed by jdmclark** 2020-11-10 14:50 UTC
Labels: invalid
