### ISSUE TITLE
Frames Per Second

### ISSUE THREAD

**Issue by jarronimo** [jdmclark/jkgfxmod#8] opened 2019-04-22 04:38 UTC
My FPS hovers in the 22 - 28 range with this mod. I get 60 fps (which I capped at 48) with dgVoodoo.

**Comment by TP555** [comment] 2019-04-22 23:58
Hi

in Jedi Knight , or Mystery of the Sith ?

in Mystery of the Sith , im get at the First Mission in the Big Hangar , too min 22FPS + MipMap Fix and Fov 120 Fix for UltraWide 2560x1080

DgVoodoo 2 , both Works with Capped 30FPS , with no Lag or Hard Perf Drops

But i think the Problem is , the Neural Textures and the JediGFXMod 2019 , makes the FPS problems , because , there are too much 16Bits Mats (Textures) , the Main Game was more Designed for 8Bit Textures !

**Comment by jarronimo** [comment] 2019-04-23 00:02
In Jedi Knight. I’m running at 4K with a 2080TI. Looks great otherwise. It’s an awesome mod.

**Comment by TP555** [comment] 2019-04-23 22:52
Re

hmm , in Jedi Knight , i had Stable 30 FPS (Capped)

But , the Mod needs alot of optimization , mayby reaches here not a Wrapper , it needs a complette new JK.exe File , which too fix the over 49FPS Problem , so that the Game runs smooth on 60FPS , and no Perf. Breaks , because 16Bit Mats/Textures.

**Comment by jdmclark** [comment] 2019-04-25 05:31
Hi @jarronimo 

Thanks for the report.

Release v0.0.10 roughly doubles framerates in local testing at 4K (due to commit c62ee70c1acf979d2cbeb923cef2603f7ecb1725). I'm marking this issue fixed on the assumption that our performance issues had the same root cause. Please re-open this issue if you continue to experience extreme low framerates.

**Closed as completed by jdmclark** 2019-04-25 05:31 UTC

**Comment by jarronimo** [comment] 2019-04-25 22:39
Thanks for the reply. I tried the new version and still get frames in the 20s at 4K. At 1080p or 1440p, it works great. I'm only seeing a slowdown at 4K.
