### ISSUE TITLE
Request: hor+ widescreen

### ISSUE THREAD

**Issue by KainXVIII** [jdmclark/jkgfxmod#41] opened 2019-11-29 09:55 UTC
Is it possible?
PS - with this ips patch https://shinyquagsire23.github.io/dk2-mots/ your mod just crashed after loading the game.

**Comment by jdmclark** [comment] 2019-11-29 20:48
Hi @KainXVIII 

Thanks for the suggestion. Unfortunately, JkGfxMod is not able to change how JK transforms the original geometry, so the FOV is always whatever JK uses internally. See #5 for original report.

Some people have had good luck fixing this with shinyquagsire's patches; others get crashes. See #13 for instance. Usually when people have reported widescreen patch crashes under JkGfxMod, it also crashes without JkGfxMod.

Closing for now as a duplicate of #5

**Closed as completed by jdmclark** 2019-11-29 20:48 UTC
Labels: duplicate, wontfix
