### ISSUE TITLE
Ram Usage seems low Overheating PC

### ISSUE THREAD

**Issue by GeneralTantor** [jdmclark/jkgfxmod#2] opened 2019-04-06 11:28 UTC
I noticed that the game does not use that much memory but with the upscale texture and what not I think it be good if the game would run with more memory is there currently a limit? The game is very laggy for me but I do not think its my PC since it barely uses any memory to run the game its at like 200MB?

**Comment by TP555** [comment] 2019-04-06 19:51
Hi

Yes 204MB ,hmm mayby it needs not more or it is a Bug yes , im notice too some short lags , but Performance is good i think , im play with a GTX950 in 2560x1080x16 , i don't know how to set 32 ! , and with Reshade 3.3.2 and with 7 Filers , i have around 42-40FPS.

Here is my setting from the  jkgm.json , can you try it

{
"resolution": [ 2560, 1080 ],
"internal_resolution": null,
"fullscreen": true,
"hud_scale": 1.5,
"max_anisotropy": 2.0,
"enable_ssao": false,
"enable_parallax": true,
"command": "jk.exe"
}

And im use this to force Proper Widescreen/UltraWide  (120Fov Mipmap)
http://jkdf2.net/index.php?page=ProjectDisplay&pid=96

I think a Precache Funtion for the Textures and another Stuff will solve the short lags  !

**Comment by GeneralTantor** [comment] 2019-04-07 10:29
Ill try that I forget to tell you the main issue is actually it overheats my computer and it shuts down half way through the first level. I thought my PC was Crap at first but then it dawn on me that since this is an old game it might have limits. So that is why I thought maybe because of the limit on RAM it can use it jumps in to more CPU power and overheats the game. It happend once with OBS on and then a few times without OBS as well that is my video recording software I use. At first I thought it was just having OBS on was to much for my PC but then it happens again with Just JK open with I also had Upscale Texture pack on and the Extension mod for Blasters and Explosions.
Upscale pack: https://www.moddb.com/mods/jedi-knight-neural-upscale-texture-pack/downloads/jedi-knight-neural-upscale-texture-pack
Explosions and Blaster fire pack: https://www.moddb.com/games/star-wars-jedi-knight-dark-forces-ii/downloads/jkgfx2019

But the laggness happened without anything installed as well have not tested if it will overheat without any material packs though... When I add the settings I will test without anything first. 

Here is my computer specs in the meantime so we can rule-out  if it is just my crappy PC.
AMD A10-5750M APU with Radeon (tm) HD Graphics 2.50 GHz
8.00 GB RAM
64 bit OS running Windows 8.1

**Comment by TP555** [comment] 2019-04-07 18:10
Re

oh , that is SAD , but that is an General Problem on the Most Notebooks , seems time to Upgrade , you can try to Clean it from some Dirt , Dust , and renew the Heat Sink , but the Peformance will ever Bad.

I had Tested with OBS Studio , 2560x1080@60FPS , Bitrate : 60000 with the NVENC (New) , 4FPS Less , i had Capped to 40FPS , because the Game runs smoother , it have some movement problems with about 46FPS , but even Caped 40FPS with OBS Studio 23 Recording 36FPS.

But i think , you will never seen the 30FPS ingame or   ?

But the Low Ram Usage is True , i have 16GB , and the Game fill just 204MB , so you can Rename the Thread  again   !

Is that your YT Channel   ?
https://www.youtube.com/channel/UCi1wIpZ9uOZr4_IW9xF8f7g

**Comment by jdmclark** [comment] 2019-04-08 01:52
Hi @GeneralTantor 

Thanks for your report. Unfortunately, the RAM usage you've reported is expected and unlikely to be the root cause of your issue. JkGfxMod does not require much system memory, but it is quite demanding on graphics hardware. Slower hardware will particularly struggle with SSAO and parallax mapping, so you should consider disabling them in your jkgm.json configuration file. If your computer regularly overheats, however, it likely requires cleaning or repair.

I've filed #6 to follow up on @TP555 's suggestion for how the excess memory in modern systems might be used to improve performance.

Otherwise, I'm closing this bug.

**Closed as completed by jdmclark** 2019-04-08 01:52 UTC

**Comment by GeneralTantor** [comment] 2019-04-08 09:44
Thanks Jonathan! yeah my computers crape lol! I was able to get lagging
down with what TP255 said but since my Laptop is very hot it can't run but
that is more on my PC then a bug... Anyways I was able to get it working on
a different laptop without issues!
