### ISSUE TITLE
Windows 10 Virus alert: Win32/Ymacco.AAAB

### ISSUE THREAD

**Issue by andwan0** [jdmclark/jkgfxmod#77] opened 2023-12-04 12:37 UTC
Windows 10 Virus alert:

Program:Win32/Ymacco.AAAB

Something we should be worried about?

**Comment by jdmclark** [comment] 2023-12-04 13:31
Hello,

Thanks for the report. Unfortunately, antivirus false positives have been an issue for this project from the beginning; in order to inject itself into the original game, JkGfxMod uses a library from Microsoft called Detours, which is also sometimes used by malware authors for similar purposes.

The JkGfxMod build used only source code from this repository and ran on Microsoft-controlled servers, which you can audit here:

https://github.com/jdmclark/jkgfxmod/actions/runs/63797777

Unfortunately, there isn't much I can do about this problem. I recommend submitting inject.exe as a false positive to your antivirus vendor.

If possible, you may also consider using [OpenJKDF2](https://github.com/shinyquagsire23/OpenJKDF2), which is a complete engine replacement that also implements JkGfxMod features.

Marking as duplicate of #51

**Closed as completed by jdmclark** 2023-12-04 13:31 UTC
Labels: duplicate, invalid
